// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgcrtKh8qGpgnVBtN87dy2QTqBMdeBgQ',
    appId: '1:1057557069485:web:336c58ab051deed228d024',
    messagingSenderId: '1057557069485',
    projectId: 'alerts-cba4e',
    authDomain: 'alerts-cba4e.firebaseapp.com',
    storageBucket: 'alerts-cba4e.appspot.com',
    measurementId: 'G-TSP6X681JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7dUG5O0mMLVYGqBv1FPZUrxFvEl7fkrA',
    appId: '1:1057557069485:android:433d396940c5ee2828d024',
    messagingSenderId: '1057557069485',
    projectId: 'alerts-cba4e',
    storageBucket: 'alerts-cba4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6THhdAhZk5PHIKPjd9DCyfyAOMsH1Wk',
    appId: '1:1057557069485:ios:b0adfb9a6fb7de8528d024',
    messagingSenderId: '1057557069485',
    projectId: 'alerts-cba4e',
    storageBucket: 'alerts-cba4e.appspot.com',
    iosClientId: '1057557069485-e3de8hktt4fmrkkjshl15g5d5h6ikkm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.alerts',
  );
}
